#!/usr/bin/env node
/**
 * WB Studio static site generator (zero dependencies).
 *
 * Reads  data/site.mjs + data/projects.json
 * Writes every HTML page (Arabic at the root, English under /en/) + sitemap.xml
 *
 * Usage:  node scripts/build.mjs
 *
 * Generated pages carry a banner comment — never edit them by hand.
 */

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import site from '../data/site.mjs';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const projects = JSON.parse(fs.readFileSync(path.join(ROOT, 'data', 'projects.json'), 'utf8')).projects;

const LANGS = ['ar', 'en'];
const HOME_HERO_SOURCE_ID = 'photo-1613490493576-7fde63acd811';

/* ───────────────────────── helpers ───────────────────────── */

const esc = (s) => String(s)
  .replaceAll('&', '&amp;').replaceAll('<', '&lt;').replaceAll('>', '&gt;')
  .replaceAll('"', '&quot;');

/** Pick the language variant of a bilingual field. */
const t = (field, lang) => (field && typeof field === 'object' && !Array.isArray(field)) ? field[lang] : field;

/** Logical path ("/work/slug/") → URL path for a language. */
const langPath = (lang, p) => (lang === 'ar' ? p : `/en${p}`);
const absUrl = (lang, p) => site.domain + langPath(lang, p);

const otherLang = (lang) => (lang === 'ar' ? 'en' : 'ar');

const waUrl = (lang) => `https://wa.me/${site.whatsappNumber}?text=${encodeURIComponent(site.waMessage[lang])}`;

const arrow = (lang) => (lang === 'ar' ? '←' : '→');

function img(image, lang, { eager = false, sizes = '100vw', className = '' } = {}) {
  const cls = className ? ` class="${className}"` : '';
  const loading = eager ? 'fetchpriority="high"' : 'loading="lazy"';
  return `<img${cls} src="${image.src}" width="${image.w}" height="${image.h}" alt="${esc(t(image.alt, lang))}" ${loading} decoding="async" />`;
}

/* ───────────────────────── document shell ───────────────────────── */

function head({ lang, title, desc, logicalPath, ogImage, jsonld = [], isHome = false }) {
  const dir = lang === 'ar' ? 'rtl' : 'ltr';
  const ogLocale = lang === 'ar' ? 'ar_SA' : 'en_US';
  const ogAlt = lang === 'ar' ? 'en_US' : 'ar_SA';
  const image = ogImage || site.ogImage;
  const ld = jsonld.length
    ? `\n  <script type="application/ld+json">${JSON.stringify({ '@context': 'https://schema.org', '@graph': jsonld })}</script>`
    : '';
  return `<!doctype html>
<!-- Generated by scripts/build.mjs — do not edit by hand. Edit data/site.mjs, data/projects.json or scripts/build.mjs, then run: node scripts/build.mjs -->
<html lang="${lang}" dir="${dir}">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width,initial-scale=1" />
  <title>${esc(title)}</title>
  <meta name="description" content="${esc(desc)}" />
  <meta name="robots" content="index, follow, max-image-preview:large, max-snippet:-1, max-video-preview:-1" />
  <meta name="author" content="Wael Bousmael" />
  <meta name="theme-color" content="#faf8f4" />
  <meta name="geo.region" content="SA-02" />
  <meta name="geo.placename" content="Jeddah" />
  <meta name="geo.position" content="21.5433;39.1728" />
  <meta name="ICBM" content="21.5433, 39.1728" />
  <link rel="canonical" href="${absUrl(lang, logicalPath)}" />
  <link rel="alternate" hreflang="ar" href="${absUrl('ar', logicalPath)}" />
  <link rel="alternate" hreflang="en" href="${absUrl('en', logicalPath)}" />
  <link rel="alternate" hreflang="x-default" href="${absUrl('ar', logicalPath)}" />
  <link rel="icon" href="/assets/icons/favicon.ico" sizes="any" />
  <link rel="apple-touch-icon" href="/assets/icons/apple-touch-icon.png" />
  <link rel="manifest" href="/manifest.webmanifest" />
  <meta property="og:type" content="website" />
  <meta property="og:site_name" content="${site.brand}" />
  <meta property="og:url" content="${absUrl(lang, logicalPath)}" />
  <meta property="og:title" content="${esc(title)}" />
  <meta property="og:description" content="${esc(desc)}" />
  <meta property="og:image" content="${image}" />
  <meta property="og:locale" content="${ogLocale}" />
  <meta property="og:locale:alternate" content="${ogAlt}" />
  <meta name="twitter:card" content="summary_large_image" />
  <meta name="twitter:title" content="${esc(title)}" />
  <meta name="twitter:description" content="${esc(desc)}" />
  <meta name="twitter:image" content="${image}" />
  <link rel="preconnect" href="https://fonts.googleapis.com" />
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
  <link href="${site.fonts[lang]}" rel="stylesheet" />
  <link rel="stylesheet" href="/assets/css/site.css" />${ld}
</head>`;
}

function header(lang, active) {
  const n = site.nav;
  const items = [
    ['work', '/work/'],
    ['approach', '/approach/'],
    ['about', '/about/'],
    ['contact', '/contact/']
  ];
  const link = ([key, p]) =>
    `<a href="${langPath(lang, p)}"${active === key ? ' aria-current="page"' : ''}>${esc(t(n[key], lang))}</a>`;
  const langLink = (cls) =>
    `<a class="${cls}" href="${langPath(otherLang(lang), activeLogicalPath)}" hreflang="${otherLang(lang)}" lang="${otherLang(lang)}" data-lang-switch="${otherLang(lang)}" aria-label="${esc(t(n.langAria, lang))}">${esc(t(n.langLabel, lang))}</a>`;

  return `<a class="skip-link" href="#main">${esc(t(n.skip, lang))}</a>
<header class="site-header">
  <div class="wrap header-inner">
    <a class="wordmark" href="${langPath(lang, '/')}" aria-label="${site.brand}">WB&nbsp;Studio</a>
    <nav class="header-nav" aria-label="${lang === 'ar' ? 'التنقل الرئيسي' : 'Primary navigation'}">
      ${items.map(link).join('\n      ')}
      ${langLink('lang-link')}
    </nav>
    <button class="nav-toggle" type="button" data-nav-toggle aria-expanded="false" aria-controls="mobileMenu" aria-label="${esc(t(n.menuOpen, lang))}">
      <span></span><span></span>
    </button>
  </div>
</header>
<div class="mobile-menu" id="mobileMenu" hidden>
  <div class="mobile-menu-head">
    <span class="wordmark">WB&nbsp;Studio</span>
    <button class="mobile-close" type="button" data-nav-close aria-label="${esc(t(n.menuClose, lang))}">✕</button>
  </div>
  <nav class="mobile-links" aria-label="${lang === 'ar' ? 'قائمة الجوال' : 'Mobile navigation'}">
    ${items.map(link).join('\n    ')}
    ${langLink('lang-link')}
  </nav>
  <div class="mobile-contact">
    <a href="${waUrl(lang)}" target="_blank" rel="noopener">${esc(t(site.footer.whatsappLabel, lang))}</a>
    <a href="${site.gmailCompose}" target="_blank" rel="noopener" dir="ltr">${site.email}</a>
  </div>
</div>`;
}

// header() needs the logical path of the page being rendered for the language link.
let activeLogicalPath = '/';

function footer(lang) {
  const f = site.footer;
  const n = site.nav;
  return `<footer class="site-footer">
  <div class="wrap footer-grid">
    <div class="footer-brand">
      <span class="wordmark">WB&nbsp;Studio</span>
      <p>${esc(t(f.tagline, lang))}</p>
    </div>
    <nav class="footer-col" aria-label="${esc(t(f.explore, lang))}">
      <p class="footer-title">${esc(t(f.explore, lang))}</p>
      <a href="${langPath(lang, '/work/')}">${esc(t(n.work, lang))}</a>
      <a href="${langPath(lang, '/approach/')}">${esc(t(n.approach, lang))}</a>
      <a href="${langPath(lang, '/about/')}">${esc(t(n.about, lang))}</a>
      <a href="${langPath(lang, '/contact/')}">${esc(t(n.contact, lang))}</a>
    </nav>
    <div class="footer-col">
      <p class="footer-title">${esc(t(f.contactTitle, lang))}</p>
      <a href="${site.gmailCompose}" target="_blank" rel="noopener" dir="ltr">${site.email}</a>
      <a href="tel:${site.phoneE164}" dir="ltr">${site.phoneDisplay}</a>
      <a href="${waUrl(lang)}" target="_blank" rel="noopener">${esc(t(f.whatsappLabel, lang))}</a>
    </div>
  </div>
  <div class="footer-bottom">
    <div class="wrap footer-bottom-inner">
      <p>© <span data-year>2026</span> ${site.brand}. ${esc(t(f.rights, lang))}</p>
      <p><a href="${langPath(lang, '/credits/')}">${esc(t(f.credits, lang))}</a></p>
      <p dir="ltr">${f.locations}</p>
    </div>
  </div>
</footer>
<script src="/assets/js/site.js" defer></script>`;
}

function contactBand(lang) {
  const c = site.contactBand;
  return `<section class="contact-band" data-reveal>
  <div class="wrap narrow centered">
    <h2 class="display">${esc(t(c.title, lang))}</h2>
    <p class="lead">${esc(t(c.text, lang))}</p>
    <div class="cta-row">
      <a class="btn btn-solid" href="${langPath(lang, '/contact/')}">${esc(t(c.primary, lang))}</a>
      <a class="btn" href="${waUrl(lang)}" target="_blank" rel="noopener">${esc(t(c.secondary, lang))}</a>
    </div>
  </div>
</section>`;
}

function projectCard(p, lang, { wide = false, eager = false } = {}) {
  const meta = [t(p.category, lang), t(p.location, lang), p.year].join(' · ');
  return `<a class="project-card${wide ? ' is-wide' : ''}" href="${langPath(lang, `/work/${p.slug}/`)}" data-reveal>
  <div class="card-media">${img(p.cover, lang, { eager })}</div>
  <div class="card-text">
    <h3>${esc(t(p.title, lang))}</h3>
    <p class="card-meta">${esc(meta)}${p.placeholder ? ` <span class="tag">${esc(t(p.status, lang))}</span>` : ''}</p>
  </div>
</a>`;
}

/* ───────────────────────── structured data ───────────────────────── */

function businessGraph(lang) {
  const d = site.domain;
  const desc = lang === 'ar'
    ? 'مهندس معماري لتصميم الفلل والمنازل الخاصة في جدة والسعودية والخليج، يبدأ العمل بمكالمة مجانية وتصور مبدئي مجاني قبل أي اتفاق مدفوع.'
    : 'Architect for private villas and homes in Jeddah, Saudi Arabia and the Gulf. Work begins with a free call and a free preliminary concept before any paid agreement.';
  return [
    {
      '@type': 'Organization', '@id': `${d}/#organization`,
      name: 'WB Studio', alternateName: 'Wael Bousmael', url: `${d}/`,
      logo: { '@type': 'ImageObject', url: `${d}/assets/icons/apple-touch-icon.png`, width: 512, height: 512 },
      image: site.ogImage, email: site.email, telephone: site.phoneE164
    },
    {
      '@type': 'WebSite', '@id': `${d}/#website`, url: `${d}/`,
      name: 'WB Studio — Wael Bousmael', inLanguage: ['ar', 'en'],
      publisher: { '@id': `${d}/#organization` }
    },
    {
      '@type': ['ProfessionalService', 'Architect', 'LocalBusiness'], '@id': `${d}/#business`,
      name: 'WB Studio — Wael Bousmael', description: desc, url: `${d}/`,
      image: site.ogImage, logo: `${d}/assets/icons/apple-touch-icon.png`,
      telephone: site.phoneE164, email: site.email,
      priceRange: '$$$', currenciesAccepted: 'SAR',
      address: { '@type': 'PostalAddress', addressLocality: 'Jeddah', addressRegion: 'Makkah Province', addressCountry: 'SA' },
      geo: { '@type': 'GeoCoordinates', latitude: 21.5433, longitude: 39.1728 },
      areaServed: [
        { '@type': 'City', name: 'Jeddah' },
        { '@type': 'Country', name: 'Saudi Arabia' },
        { '@type': 'Place', name: 'Gulf Cooperation Council (GCC)' }
      ],
      knowsLanguage: ['ar', 'en'],
      openingHoursSpecification: [{
        '@type': 'OpeningHoursSpecification',
        dayOfWeek: ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday'],
        opens: '09:00', closes: '18:00'
      }],
      founder: { '@id': `${d}/#wael` }, employee: { '@id': `${d}/#wael` },
      parentOrganization: { '@id': `${d}/#organization` }
    },
    {
      '@type': 'Person', '@id': `${d}/#wael`,
      name: 'Wael Bousmael', alternateName: 'وائل بو سماعيل', jobTitle: 'Architect',
      description: lang === 'ar'
        ? 'معماري ومنسق BIM بخبرة تتجاوز 12 عامًا في تصميم الفلل السكنية الفاخرة، من الفكرة الأولى حتى مخططات التنفيذ.'
        : 'Architect and BIM coordinator with 12+ years of experience in luxury residential villas, from first concept to construction documentation.',
      knowsAbout: ['Architecture', 'Villa design', 'BIM coordination', 'Residential design'],
      worksFor: { '@id': `${d}/#business` }, url: absUrl(lang, '/about/')
    }
  ];
}

function breadcrumb(lang, trail) {
  return {
    '@type': 'BreadcrumbList',
    itemListElement: trail.map(([name, p], i) => ({
      '@type': 'ListItem', position: i + 1, name, item: absUrl(lang, p)
    }))
  };
}

/* ───────────────────────── pages ───────────────────────── */

function renderHome(lang) {
  const h = site.home;
  const featured = projects.filter((p) => p.featured).slice(0, 3);
  const steps = site.approach.steps;
  return `${head({
    lang,
    title: t(h.seoTitle, lang),
    desc: t(h.seoDesc, lang),
    logicalPath: '/',
    jsonld: businessGraph(lang)
  })}
<body data-page="home">
${header(lang, null)}
<main id="main">
  <section class="hero" data-reveal>
    <div class="wrap">
      <p class="eyebrow">${esc(t(h.eyebrow, lang))}</p>
      <h1 class="display-xl">${esc(t(h.h1, lang))}</h1>
      <p class="lead measure">${esc(t(h.positioning, lang))}</p>
      <p class="offer measure">${esc(t(site.offer, lang))}</p>
      <div class="cta-row">
        <a class="btn btn-solid" href="${waUrl(lang)}" target="_blank" rel="noopener">${esc(t(h.ctaWhatsapp, lang))}</a>
        <a class="btn" href="${langPath(lang, '/work/')}">${esc(t(h.ctaWork, lang))}</a>
      </div>
    </div>
  </section>
  <div class="bleed" data-reveal>${img(h.heroImage, lang, { eager: true })}</div>

  <section class="section" data-reveal>
    <div class="wrap">
      <div class="section-head">
        <h2 class="display">${esc(t(h.selectedTitle, lang))}</h2>
        <a class="text-link" href="${langPath(lang, '/work/')}">${esc(t(h.allWork, lang))} ${arrow(lang)}</a>
      </div>
      <div class="project-grid home-grid">
        ${featured.map((p, i) => projectCard(p, lang, { wide: i === 0 })).join('\n        ')}
      </div>
    </div>
  </section>

  <section class="section divided" data-reveal>
    <div class="wrap">
      <div class="section-head">
        <h2 class="display">${esc(t(h.approachTitle, lang))}</h2>
        <a class="text-link" href="${langPath(lang, '/approach/')}">${esc(t(h.approachMore, lang))} ${arrow(lang)}</a>
      </div>
      <p class="lead measure">${esc(t(h.approachLead, lang))}</p>
      <ol class="steps">
        ${steps.map((s, i) => `<li>
          <span class="step-num">0${i + 1}</span>
          <h3>${esc(t(s.title, lang))}</h3>
          <p>${esc(t(s.text, lang))}</p>
        </li>`).join('\n        ')}
      </ol>
    </div>
  </section>

  <section class="section divided" data-reveal>
    <div class="wrap about-preview">
      <div class="about-portrait">
        ${img(site.about.portrait, lang)}
      </div>
      <div>
        <h2 class="display">${esc(t(h.aboutTitle, lang))}</h2>
        <p class="lead">${esc(t(h.aboutText, lang))}</p>
        <a class="text-link" href="${langPath(lang, '/about/')}">${esc(t(h.aboutMore, lang))} ${arrow(lang)}</a>
      </div>
    </div>
  </section>

  ${contactBand(lang)}
</main>
${footer(lang)}
</body>
</html>`;
}

function renderWork(lang) {
  const w = site.work;
  return `${head({
    lang,
    title: t(w.seoTitle, lang),
    desc: t(w.seoDesc, lang),
    logicalPath: '/work/',
    jsonld: [breadcrumb(lang, [[lang === 'ar' ? 'الرئيسية' : 'Home', '/'], [t(site.nav.work, lang), '/work/']])]
  })}
<body data-page="work">
${header(lang, 'work')}
<main id="main">
  <section class="page-head" data-reveal>
    <div class="wrap">
      <h1 class="display-xl">${esc(t(w.h1, lang))}</h1>
      <p class="note measure">${esc(t(w.note, lang))} <a href="${langPath(lang, '/credits/')}">${esc(t(w.noteLink, lang))}</a>.</p>
    </div>
  </section>
  <section class="section" data-reveal>
    <div class="wrap">
      <div class="project-grid">
        ${projects.map((p, i) => projectCard(p, lang, { eager: i < 2 })).join('\n        ')}
      </div>
    </div>
  </section>
  ${contactBand(lang)}
</main>
${footer(lang)}
</body>
</html>`;
}

function renderProject(p, lang) {
  const pr = site.project;
  const idx = projects.indexOf(p);
  const next = projects[(idx + 1) % projects.length];
  const metaTitle = `${t(p.title, lang)} — ${t(p.category, lang)} · ${t(p.location, lang)} | ${site.brand}`;
  const gallery = p.gallery.map((g) => {
    const isWide = g.w >= g.h;
    return `<figure class="${isWide ? 'g-wide' : 'g-tall'}" data-reveal>${img(g, lang)}</figure>`;
  }).join('\n        ');
  const details = [
    [pr.location, t(p.location, lang)],
    [pr.year, String(p.year)],
    [pr.category, t(p.category, lang)],
    [pr.status, t(p.status, lang)],
    [pr.services, t(p.services, lang).join(' · ')]
  ];
  return `${head({
    lang,
    title: metaTitle,
    desc: t(p.excerpt, lang),
    logicalPath: `/work/${p.slug}/`,
    ogImage: site.domain + p.cover.src,
    jsonld: [breadcrumb(lang, [
      [lang === 'ar' ? 'الرئيسية' : 'Home', '/'],
      [t(site.nav.work, lang), '/work/'],
      [t(p.title, lang), `/work/${p.slug}/`]
    ])]
  })}
<body data-page="project">
${header(lang, 'work')}
<main id="main">
  <article>
    <section class="page-head" data-reveal>
      <div class="wrap">
        <p class="crumb"><a href="${langPath(lang, '/work/')}">${arrow(lang) === '→' ? '←' : '→'} ${esc(t(pr.backToWork, lang))}</a></p>
        <h1 class="display-xl">${esc(t(p.title, lang))}</h1>
        <p class="card-meta">${esc([t(p.category, lang), t(p.location, lang), p.year].join(' · '))}${p.placeholder ? ` <span class="tag">${esc(t(p.status, lang))}</span>` : ''}</p>
      </div>
    </section>
    <div class="wrap" data-reveal>
      <figure class="project-cover">${img(p.cover, lang, { eager: true })}</figure>
    </div>
    <section class="section-sm" data-reveal>
      <div class="wrap narrow">
        <p class="thesis">${esc(t(p.thesis, lang))}</p>
      </div>
    </section>
    <section class="section-sm" data-reveal>
      <div class="wrap narrow">
        <dl class="details">
          ${details.map(([l, v]) => `<div class="details-row"><dt>${esc(t(l, lang))}</dt><dd>${esc(v)}</dd></div>`).join('\n          ')}
        </dl>
      </div>
    </section>
    <section class="section-sm" data-reveal>
      <div class="wrap narrow flow">
        ${p.body.map((para) => `<p>${esc(t(para, lang))}</p>`).join('\n        ')}
      </div>
    </section>
    <section class="section-sm">
      <div class="wrap">
        <div class="gallery">
        ${gallery}
        </div>
        ${p.placeholder ? `<p class="note gallery-note">${esc(t(pr.galleryNote, lang))} <a href="${langPath(lang, '/credits/')}">${esc(t(pr.galleryNoteLink, lang))}</a>.</p>` : ''}
      </div>
    </section>
    <section class="section-sm divided" data-reveal>
      <div class="wrap next-project">
        <p class="eyebrow">${esc(t(pr.nextProject, lang))}</p>
        <a class="next-link display" href="${langPath(lang, `/work/${next.slug}/`)}">${esc(t(next.title, lang))} ${arrow(lang)}</a>
      </div>
    </section>
  </article>
  ${contactBand(lang)}
</main>
${footer(lang)}
</body>
</html>`;
}

function renderApproach(lang) {
  const a = site.approach;
  return `${head({
    lang,
    title: t(a.seoTitle, lang),
    desc: t(a.seoDesc, lang),
    logicalPath: '/approach/',
    jsonld: [breadcrumb(lang, [[lang === 'ar' ? 'الرئيسية' : 'Home', '/'], [t(site.nav.approach, lang), '/approach/']])]
  })}
<body data-page="approach">
${header(lang, 'approach')}
<main id="main">
  <section class="page-head" data-reveal>
    <div class="wrap">
      <h1 class="display-xl">${esc(t(a.h1, lang))}</h1>
      <p class="lead measure">${esc(t(a.intro, lang))}</p>
    </div>
  </section>
  <section class="section divided" data-reveal>
    <div class="wrap">
      <h2 class="display">${esc(t(a.servicesTitle, lang))}</h2>
      <div class="service-list">
        ${a.services.map((s) => `<div class="service-row" data-reveal>
          <h3>${esc(t(s.title, lang))}</h3>
          <p>${esc(t(s.text, lang))}</p>
        </div>`).join('\n        ')}
      </div>
    </div>
  </section>
  <section class="section divided" data-reveal>
    <div class="wrap">
      <h2 class="display">${esc(t(a.processTitle, lang))}</h2>
      <ol class="steps">
        ${a.steps.map((s, i) => `<li data-reveal>
          <span class="step-num">0${i + 1}</span>
          <h3>${esc(t(s.title, lang))}</h3>
          <p>${esc(t(s.text, lang))}</p>
        </li>`).join('\n        ')}
      </ol>
      <p class="offer measure">${esc(t(site.offer, lang))}</p>
    </div>
  </section>
  ${contactBand(lang)}
</main>
${footer(lang)}
</body>
</html>`;
}

function renderAbout(lang) {
  const a = site.about;
  return `${head({
    lang,
    title: t(a.seoTitle, lang),
    desc: t(a.seoDesc, lang),
    logicalPath: '/about/',
    jsonld: [...businessGraph(lang), breadcrumb(lang, [[lang === 'ar' ? 'الرئيسية' : 'Home', '/'], [t(site.nav.about, lang), '/about/']])]
  })}
<body data-page="about">
${header(lang, 'about')}
<main id="main">
  <section class="page-head" data-reveal>
    <div class="wrap">
      <h1 class="display-xl">${esc(t(a.h1, lang))}</h1>
      <p class="lead measure">${esc(t(a.intro, lang))}</p>
    </div>
  </section>
  <section class="section divided" data-reveal>
    <div class="wrap about-grid">
      <div class="about-portrait">${img(a.portrait, lang)}</div>
      <div class="flow">
        <h2 class="display">${esc(t(a.name, lang))}</h2>
        <p>${esc(t(a.bio, lang))}</p>
        <h3>${esc(t(a.practiceTitle, lang))}</h3>
        <p>${esc(t(a.practiceText, lang))}</p>
      </div>
    </div>
  </section>
  <section class="section-sm divided" data-reveal>
    <div class="wrap narrow">
      <dl class="details">
        ${a.facts.map((f) => `<div class="details-row"><dt>${esc(t(f.label, lang))}</dt><dd>${esc(t(f.value, lang))}</dd></div>`).join('\n        ')}
      </dl>
    </div>
  </section>
  ${contactBand(lang)}
</main>
${footer(lang)}
</body>
</html>`;
}

function renderContact(lang) {
  const c = site.contactPage;
  const f = site.form;
  const faqLd = {
    '@type': 'FAQPage',
    inLanguage: lang,
    mainEntity: site.faq.map((item) => ({
      '@type': 'Question', name: t(item.q, lang),
      acceptedAnswer: { '@type': 'Answer', text: t(item.a, lang) }
    }))
  };
  return `${head({
    lang,
    title: t(c.seoTitle, lang),
    desc: t(c.seoDesc, lang),
    logicalPath: '/contact/',
    jsonld: [faqLd, breadcrumb(lang, [[lang === 'ar' ? 'الرئيسية' : 'Home', '/'], [t(site.nav.contact, lang), '/contact/']])]
  })}
<body data-page="contact">
${header(lang, 'contact')}
<main id="main">
  <section class="page-head" data-reveal>
    <div class="wrap">
      <h1 class="display-xl">${esc(t(c.h1, lang))}</h1>
      <p class="lead measure">${esc(t(c.intro, lang))}</p>
      <div class="cta-row">
        <a class="btn btn-solid" href="${waUrl(lang)}" target="_blank" rel="noopener">${esc(t(c.whatsappCta, lang))}</a>
      </div>
      <div class="direct-contact">
        <p class="footer-title">${esc(t(c.directTitle, lang))}</p>
        <a href="${site.gmailCompose}" target="_blank" rel="noopener" dir="ltr">${site.email}</a>
        <a href="tel:${site.phoneE164}" dir="ltr">${site.phoneDisplay}</a>
      </div>
    </div>
  </section>

  <section class="section divided" data-reveal>
    <div class="wrap form-wrap">
      <h2 class="display">${esc(t(f.title, lang))}</h2>
      <p class="note">${esc(t(f.subtitle, lang))}</p>
      <form id="leadForm" action="${site.formAction}" method="POST" novalidate>
        <input type="hidden" name="_subject" value="WB Studio - Plot Details Free Call Request" />
        <input type="hidden" name="_template" value="table" />
        <input type="hidden" name="_captcha" value="false" />

        <label for="name"><span>${esc(t(f.name, lang))}</span> <span class="required-mark" aria-hidden="true">*</span></label>
        <input id="name" name="name" type="text" autocomplete="name" placeholder="${esc(t(f.namePh, lang))}" required />

        <label for="phone"><span>${esc(t(f.phone, lang))}</span> <span class="required-mark" aria-hidden="true">*</span></label>
        <input id="phone" name="phone" type="tel" autocomplete="tel" placeholder="${esc(t(f.phonePh, lang))}" pattern="^[+\\d\\s]{7,}$" required />

        <label for="email"><span>${esc(t(f.email, lang))}</span> <span class="required-mark" aria-hidden="true">*</span></label>
        <input id="email" name="email" type="email" autocomplete="email" placeholder="${esc(t(f.emailPh, lang))}" required />

        <div class="form-row">
          <div class="field-group">
            <label for="location">${esc(t(f.location, lang))}</label>
            <input id="location" name="location" type="text" placeholder="${esc(t(f.locationPh, lang))}" />
          </div>
          <div class="field-group">
            <label for="maps">${esc(t(f.maps, lang))}</label>
            <input id="maps" name="maps" type="url" placeholder="${esc(t(f.mapsPh, lang))}" />
          </div>
        </div>
        <p class="form-helper">${esc(t(f.locationHelper, lang))}</p>

        <label for="budget">${esc(t(f.budget, lang))}</label>
        <select id="budget" name="budget">
          <option value="">${esc(t(f.budgetPh, lang))}</option>
          ${f.budgetOptions[lang].map((o) => `<option>${esc(o)}</option>`).join('\n          ')}
        </select>

        <button class="btn btn-solid" type="submit">${esc(t(f.submit, lang))}</button>
        <p id="formFeedback" class="form-feedback" aria-live="polite"
           data-msg-success="${esc(t(f.success, lang))}"
           data-msg-error="${esc(t(f.error, lang))}"></p>
      </form>
    </div>
  </section>

  <section class="section divided" data-reveal>
    <div class="wrap narrow">
      <h2 class="display">${esc(t(c.faqTitle, lang))}</h2>
      <div class="faq">
        ${site.faq.map((item) => `<details>
          <summary>${esc(t(item.q, lang))}</summary>
          <p>${esc(t(item.a, lang))}</p>
        </details>`).join('\n        ')}
      </div>
    </div>
  </section>
</main>
${footer(lang)}
<script>window.GOOGLE_MAPS_API_KEY = window.GOOGLE_MAPS_API_KEY || '';</script>
<script src="/assets/js/contact.js" defer></script>
</body>
</html>`;
}

function renderCredits(lang) {
  const c = site.credits;
  const src = (id) => `https://images.unsplash.com/${id}`;
  const rows = projects.map((p) => {
    const images = [p.cover, ...p.gallery];
    return `<div class="credit-block">
      <h2>${esc(t(p.title, lang))}</h2>
      <ul>
        ${images.map((i) => `<li><span dir="ltr">${i.src.split('/').pop()}</span> — <a href="${src(i.sourceId)}" target="_blank" rel="noopener">${esc(t(c.sourceLabel, lang))}</a></li>`).join('\n        ')}
      </ul>
    </div>`;
  }).join('\n      ');
  return `${head({
    lang,
    title: t(c.seoTitle, lang),
    desc: t(c.seoDesc, lang),
    logicalPath: '/credits/'
  })}
<body data-page="credits">
${header(lang, null)}
<main id="main">
  <section class="page-head" data-reveal>
    <div class="wrap narrow">
      <h1 class="display-xl">${esc(t(c.h1, lang))}</h1>
      <p class="lead">${esc(t(c.intro, lang))}</p>
      <p class="note">${esc(t(c.licenseNote, lang))}</p>
    </div>
  </section>
  <section class="section-sm" data-reveal>
    <div class="wrap narrow credits-list">
      <div class="credit-block">
        <h2>${esc(t(c.heroLabel, lang))}</h2>
        <ul><li><span dir="ltr">home-hero.webp</span> — <a href="${src(HOME_HERO_SOURCE_ID)}" target="_blank" rel="noopener">${esc(t(c.sourceLabel, lang))}</a></li></ul>
      </div>
      ${rows}
    </div>
  </section>
</main>
${footer(lang)}
</body>
</html>`;
}

/* ───────────────────────── sitemap ───────────────────────── */

function renderSitemap() {
  const today = new Date().toISOString().slice(0, 10);
  const logicalPaths = ['/', '/work/', ...projects.map((p) => `/work/${p.slug}/`), '/approach/', '/about/', '/contact/', '/credits/'];
  const entries = [];
  for (const p of logicalPaths) {
    for (const lang of LANGS) {
      entries.push(`  <url>
    <loc>${absUrl(lang, p)}</loc>
    <lastmod>${today}</lastmod>
    <xhtml:link rel="alternate" hreflang="ar" href="${absUrl('ar', p)}"/>
    <xhtml:link rel="alternate" hreflang="en" href="${absUrl('en', p)}"/>
    <xhtml:link rel="alternate" hreflang="x-default" href="${absUrl('ar', p)}"/>
  </url>`);
    }
  }
  return `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"
        xmlns:xhtml="http://www.w3.org/1999/xhtml">
${entries.join('\n')}
</urlset>
`;
}

/* ───────────────────────── write everything ───────────────────────── */

function write(relPath, html) {
  const full = path.join(ROOT, relPath);
  fs.mkdirSync(path.dirname(full), { recursive: true });
  fs.writeFileSync(full, html, 'utf8');
  console.log('  wrote', relPath);
}

console.log('Building WB Studio…');
for (const lang of LANGS) {
  const prefix = lang === 'ar' ? '' : 'en/';

  activeLogicalPath = '/';
  write(`${prefix}index.html`, renderHome(lang));

  activeLogicalPath = '/work/';
  write(`${prefix}work/index.html`, renderWork(lang));

  for (const p of projects) {
    activeLogicalPath = `/work/${p.slug}/`;
    write(`${prefix}work/${p.slug}/index.html`, renderProject(p, lang));
  }

  activeLogicalPath = '/approach/';
  write(`${prefix}approach/index.html`, renderApproach(lang));

  activeLogicalPath = '/about/';
  write(`${prefix}about/index.html`, renderAbout(lang));

  activeLogicalPath = '/contact/';
  write(`${prefix}contact/index.html`, renderContact(lang));

  activeLogicalPath = '/credits/';
  write(`${prefix}credits/index.html`, renderCredits(lang));
}
write('sitemap.xml', renderSitemap());
console.log(`Done: ${LANGS.length * (6 + projects.length)} pages + sitemap.xml`);
